# Generated by Django 2.2 on 2024-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='catName',
            new_name='name',
        ),
    ]
