# Generated by Django 2.2 on 2024-03-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240321_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='numberOfCats',
        ),
    ]
