# Generated by Django 2.2 on 2024-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_numberofcats'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='numberOfCats',
            field=models.IntegerField(default=0),
        ),
    ]
